name: Build and Deploy Kotomi

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: |
          go test ./... -v -cover

      - name: Read VERSION and metadata
        id: vars
        run: |
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - name: Set up gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Docker login with access token
        run: |
            echo "Logging in manually to Artifact Registry"
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ secrets.GCP_REGION }}-docker.pkg.dev
      - name: Print Docker config
        run: cat ~/.docker/config.json

      - name: Build and push Docker image
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kotomi/kotomi:${{ steps.vars.outputs.version }}"
          docker build -t "$IMAGE" \
            --build-arg VERSION=${{ steps.vars.outputs.version }} \
            --build-arg COMMIT=${{ steps.vars.outputs.commit }} \
            --build-arg BUILD_TIME=${{ steps.vars.outputs.build_time }} \
            .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        if: false
        run: |
          echo "Deploying ${{ secrets.GCP_REGION}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kotomi/kotomi:${{ steps.vars.outputs.version }} to Cloud Run"
          gcloud run deploy kotomi-prod \
            --image ${{ secrets.GCP_REGION}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kotomi/kotomi:${{ steps.vars.outputs.version }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
